name: clarkbuttons
description: "A new Flutter project."

publish_to:

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/img.jpg
    - images/titus.gif
    - images/warhammer.gif
    - images/fbt.gif

  fonts:
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-VariableFont.ttf

    - family: Sixtyfour
      fonts:
        - asset: fonts/SixtyfourConvergence-Regular-VariableFont_BLED,SCAN,XELA,YELA.ttf

    - family: Six
      fonts:
        - asset: fonts/SixtyfourConvergence-Regular.ttf
